name: Update
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 8,20 * * *'

jobs:
  webhook-update:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the "workflow" branch
        uses: actions/checkout@v4
        with:
          ref: workflow
          fetch-depth: 1

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Download dependencies
        run: |
          pip install -r requirements.txt

      - name: Update SuperTux webhook
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_SUPERTUX_URL }}
        run: |
          python runbot.py --config=config/supertux.json --webhook=$DISCORD_WEBHOOK_URL
          python runbot.py --config=config/supertux_ce.json --webhook=$DISCORD_WEBHOOK_URL

      - name: Stage updated run files
        run: |
          git add runs/
          git diff --staged
          RUNS_UPDATED=true
          if git diff --staged --exit-code; then
            RUNS_UPDATED=false
          fi
          echo "RUNS_UPDATED=$(echo $RUNS_UPDATED)" >> $GITHUB_ENV

      - name: Push updated run files
        if: ${{ env.RUNS_UPDATED == 'true' }}
        run: |
          git config --global user.email "speedrun-webhook-bot"
          git config --global user.name "Speedrun Webhook Bot"
          git commit -m "Update run files"
          git push origin HEAD:workflow
