#  SuperTux
#  Copyright (C) 2024 Tobias Markus
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 3
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

name: Update
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 8,20 * * *'

jobs:
  webhook-update:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the "workflow" branch
        uses: actions/checkout@v4
        with:
          ref: workflow
          fetch-depth: 1

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Download dependencies
        run: |
          pip install -r requirements.txt

      - name: Update SuperTux webhook
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_SUPERTUX_URL }}
        run: |
          python runbot.py --config=config/supertux.json --webhook=$DISCORD_WEBHOOK_URL

      - name: Push updated run files
        run: |
          git config --global user.email "speedrun-webhook-bot"
          git config --global user.name "Speedrun Webhook Bot"
          git add runs/
          git diff --staged
          git commit -m "Update run files"
          git push origin HEAD:workflow
